-- 코드를 입력하세요
# SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.created_date,'%Y-%m-%d') AS CREATED_DATE
# from USED_GOODS_BOARD AS A
# INNER JOIN USED_GOODS_REPLY AS B
# ON A.BOARD_ID = B.BOARD_ID
# WHERE B.CREATED_DATE LIKE '2022-10%'
# ORDER BY B.CREATED_DATE asc, A.TITLE asc

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, 
DATE_FORMAT(R.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS B  
INNER JOIN USED_GOODS_REPLY AS R 
ON B.BOARD_ID = R.BOARD_ID 
-- WHERE MONTH(B.CREATED_DATE) = 10
WHERE B.CREATED_DATE like '2022-10%'
ORDER BY R.CREATED_DATE ASC,  B.TITLE ASC;
